services:
  api:
    build:
      context: ../
      dockerfile: apps/api/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:pass@db:5432/seether
      - REDIS_URL=redis://redis:6379
    depends_on:
      - db
      - redis

  worker:
    build:
      context: ../
      dockerfile: apps/worker/Dockerfile
    environment:
      - DATABASE_URL=postgresql://user:pass@db:5432/seether
      - REDIS_URL=redis://redis:6379
    depends_on:
      - db
      - redis

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: seether
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine

volumes:
  postgres_data:
